added marc bohler
dice-group/dice-website pull request #453
Opened 2023-02-07 16:20 UTC by mcb5637

2023-02-07 16:27 UTC, bigerl requested changes

2023-02-07 16:27 UTC, bigerl commented on data/people/MarcBohler.ttl
> +  schema:role dice:ResearchStaff ;
role is `dice:StudentResearcher`

2023-02-08 11:52 UTC, mcb5637 commented on data/people/MarcBohler.ttl
> +  schema:role dice:ResearchStaff ;
fixed

2023-02-08 15:39 UTC, bigerl approved these changes

2023-02-08 15:40 UTC, merged