Create JonasWagner.ttl
dice-group/dice-website pull request #564
Opened 2024-11-04 14:38 UTC by zumpious

2024-11-15 09:34 UTC, bigerl requested changes
Hi Jonas,
your RDF was malformed. I've suggested a fix. Please ask your supervisor afterwards to squash-merge the changes.

2024-11-15 09:34 UTC, bigerl commented on data/people/JonasWagner.ttl
> +  schema:content """
```suggestion
  schema:publicationTag "" ;
  schema:content """
```
```suggestion
  schema:photo "wagner.jpg" . 
```

2024-11-18 11:07 UTC, zumpious commented
Hi @Perevalov , can squash-merge my PR?

2024-12-02 17:24 UTC, MichaelRoeder commented
Hi Jonas,

You may want to double check your picture. I would suggest to cut the right and lower part a little bit, so that your face is more or less in the center of the picture (but still has some space around it). The page will later on tell your browser to form a circle on top of the picture (see https://dice-research.org/team/), which may look a little bit odd with your current picture (although I didn't try it :sweat_smile: ).

When you are done (or you are happy with the picture as it is), please ping me and I will merge your changes :wink:

2024-12-04 10:32 UTC, merged